export interface Employer {
  name: string;
  city: string;
  description: string;
  industry: string;
  hiring: boolean;
  careersUrl: string;
}

export const EMPLOYERS: Employer[] = [
  {
    name: "RBC",
    city: "Toronto",
    description: "Canada's largest bank by market capitalization, headquartered in Toronto.",
    industry: "Banking & Financial Services",
    hiring: true,
    careersUrl: "https://jobs.rbc.com/ca/en",
  },
  {
    name: "TD Bank Group",
    city: "Toronto",
    description: "Leading North American financial services firm, headquartered in Toronto.",
    industry: "Banking & Financial Services",
    hiring: true,
    careersUrl: "https://careers.td.com",
  },
  {
    name: "Scotiabank",
    city: "Toronto",
    description: "Multinational bank headquartered in Toronto, operating across the Americas.",
    industry: "Banking & Financial Services",
    hiring: true,
    careersUrl: "https://jobs.scotiabank.com",
  },
  {
    name: "Rogers Communications",
    city: "Toronto",
    description: "Telecom and media company headquartered in Toronto.",
    industry: "Telecom & Media",
    hiring: true,
    careersUrl: "https://jobs.rogers.com",
  },
  {
    name: "University Health Network",
    city: "Toronto",
    description: "Canada's largest research hospital network — Toronto General, Toronto Western, Princess Margaret and more.",
    industry: "Healthcare",
    hiring: true,
    careersUrl: "https://www.uhn.ca/corporate/Careers",
  },
  {
    name: "Coca-Cola Canada Bottling",
    city: "Toronto",
    description: "Canada's national Coca-Cola bottler, headquartered in Toronto.",
    industry: "Food & Beverage Manufacturing",
    hiring: true,
    careersUrl: "https://cokecanada.com/careers/",
  },
  {
    name: "Microsoft Canada",
    city: "Mississauga",
    description: "Canadian headquarters of Microsoft, based in Mississauga.",
    industry: "Technology",
    hiring: true,
    careersUrl: "https://careers.microsoft.com",
  },
  {
    name: "PepsiCo Canada",
    city: "Mississauga",
    description: "Canadian headquarters of PepsiCo, including Frito-Lay Canada, based in Mississauga.",
    industry: "Food & Beverage Manufacturing",
    hiring: true,
    careersUrl: "https://www.pepsicojobs.com/main/northamerica/canada",
  },
  {
    name: "Maple Leaf Foods",
    city: "Mississauga",
    description: "One of Canada's largest food processing companies, headquartered in Mississauga.",
    industry: "Food Manufacturing",
    hiring: true,
    careersUrl: "https://www.mapleleaffoods.com/careers/",
  },
  {
    name: "Hewlett Packard Enterprise Canada",
    city: "Mississauga",
    description: "Canadian headquarters of HPE, based in Mississauga.",
    industry: "Technology",
    hiring: true,
    careersUrl: "https://careers.hpe.com",
  },
  {
    name: "General Mills Canada",
    city: "Mississauga",
    description: "Canadian corporate office of the global food manufacturer, based in Mississauga.",
    industry: "Food Manufacturing",
    hiring: true,
    careersUrl: "https://careers.generalmills.com",
  },
  {
    name: "Walmart Canada",
    city: "Mississauga",
    description: "Walmart's Canadian head office (Store Support Centre), based in Mississauga.",
    industry: "Retail",
    hiring: true,
    careersUrl: "https://careers.walmart.ca",
  },
  {
    name: "Loblaw Companies",
    city: "Brampton",
    description: "Canada's largest retailer and grocer, headquartered in Brampton.",
    industry: "Retail",
    hiring: true,
    careersUrl: "https://careers.loblaw.ca",
  },
  {
    name: "Maple Lodge Farms",
    city: "Brampton",
    description: "Canada's largest independent, family-owned chicken processor, headquartered in Brampton.",
    industry: "Food Manufacturing",
    hiring: true,
    careersUrl: "https://maplelodgefarms.com/careers/",
  },
  {
    name: "Amazon Canada Fulfillment",
    city: "Brampton",
    description: "Amazon fulfillment centre operations in Brampton.",
    industry: "Logistics & E-commerce",
    hiring: true,
    careersUrl: "https://hiring.amazon.ca",
  },
  {
    name: "Canadian Tire Distribution Centre",
    city: "Brampton",
    description: "Canadian Tire's A.J. Billes distribution centre in Brampton.",
    industry: "Retail & Distribution",
    hiring: true,
    careersUrl: "https://corp.canadiantire.ca/English/careers/distribution-centres/default.aspx",
  },
  {
    name: "City of Brampton",
    city: "Brampton",
    description: "Municipal government of Brampton — named one of Canada's Best Employers for 2026 by Forbes.",
    industry: "Government",
    hiring: true,
    careersUrl: "https://www.brampton.ca/EN/City-Hall/Employment",
  },
  {
    name: "William Osler Health System",
    city: "Brampton",
    description: "Ontario's largest community hospital network, including Brampton Civic Hospital.",
    industry: "Healthcare",
    hiring: true,
    careersUrl: "https://www.williamoslerhs.ca/who-we-are/careers/",
  },
];
